# Generated by Django 3.2.4 on 2023-11-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleimage', models.ImageField(null=True, upload_to='static/Vehicle/')),
                ('rent', models.IntegerField(null=True)),
                ('vehicle1', models.CharField(max_length=100, null=True)),
                ('vehicle2', models.CharField(max_length=100, null=True)),
                ('vehicle3', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
