# Generated by Django 3.2.4 on 2023-11-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_ourservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/testimonials/')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
